#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd $SCRIPT_DIR

if [ -d .bundle ]; then
  RUBY='bundle exec ruby'
else
  RUBY='ruby'
fi

$RUBY cheatcmd.rb "$@" #| bat --language=markdown