# frozen_string_literal: true

source "https://rubygems.org"

gem "commonmarker"

gem 'sorbet', :group => :development
gem 'sorbet-runtime'
gem 'tapioca', require: false, :group => [:development, :test]
