#!/usr/bin/env ruby
# coding:utf-8


PATH = ENV["PATH"]

require 'open3'
require 'pp'

require 'bundler'
Bundler.require

module Main

require 'pathname'
$: << FILE_DIR = (Pathname(File.readlink(__FILE__)) rescue Pathname(__FILE__)).dirname.expand_path 

  Commands = [:init, :help, :install, :restore]
  FILE = File.basename(__FILE__)

  unless Commands.include?(COMMAND =  ARGV[0]&.to_sym) then
    $stderr.puts <<-"EOF"
  Usage:
  $ #{FILE} command [opts..]

  commands:
    init    [os_version workspace_dir usr_dir]  : init current dir
    restore [workspace_dir]                     : restore configs
    install [target_dir]                        : install
  EOF
    exit 1
  end
  #pp $: 
  require "lib/#{COMMAND}" if (Commands.include? COMMAND)
end
