# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

group :html do
  gem "oga"
  gem "pry"
  gem "pry-coolline"
  gem "json"
end

group :develop do
  gem "irb"
  gem "rdoc"
  gem "htmlbeautifier"
  gem "rake"
  gem "iruby"
end

gem "google-apis-youtube_v3"
